version: "3.8"
services:
  e2e:
    image: cypress
    build: ../e2e
    container_name: cypress
    network_mode: 'host'
    # depends_on:
    #   - client
    #   - envoy
    #   - mock-server
    environment:
      - CYPRESS_baseUrl=http://localhost:3000/
      - CYPRESS_browser=chrome
    command: npx cypress run
    volumes:
      - ../e2e/cypress:/app/cypress
      - ../e2e/cypress.json:/app/cypress.json